### ISSUE TITLE
환경설정 구축

### ISSUE THREAD

**Issue by yunki-kim** [git-test-organi/git-test#1]
## Description

깃 연습 프로젝트 시작을 위한 환경설정 구축

## Tasks

- [ ] 이슈 템플릿 작성
- [ ] 풀 리퀘스트 템플릿 작성
- [ ] 리드미 템플릿 작성
- [ ] Projects 생성

## References

- [card-monkey](https://github.com/card-monkey/card-monkey-BE)
